ext3_problem.pddl

step    0: ANYADIR_LIBRO_PREDECESOR_A_LEER L7 L1
        1: ANYADIR_LIBRO_PREDECESOR_A_LEER L1 L2
        2: ASIGNAR_LIBRO_PARALELO L7 M1
        3: ASIGNAR_LIBRO_PREDECESOR L1 M11
        4: ASIGNAR_LIBRO_PREDECESOR L2 M12
        5: ASIGNAR_LIBRO_PREDECESOR L3 M10
        6: ASIGNAR_LIBRO_PREDECESOR L6 M9
        7: REACH-GOAL



ext3_problem_2.pddl

step    0: ASIGNAR_LIBRO_PREDECESOR L3 M2
        1: ANYADIR_LIBRO_PREDECESOR_A_LEER L7 L1
        2: ASIGNAR_LIBRO_PREDECESOR L7 M2
        3: ANYADIR_LIBRO_PREDECESOR_A_LEER L5 L6
        4: ASIGNAR_LIBRO_PREDECESOR L5 M3
        5: ASIGNAR_LIBRO_PREDECESOR L6 M5
        6: ANYADIR_LIBRO_PREDECESOR_A_LEER L1 L2
        7: ASIGNAR_LIBRO_PREDECESOR L1 M3
        8: ASIGNAR_LIBRO_PREDECESOR L2 M4
        9: REACH-GOAL



ext3_problem_3.pddl

step    0: ASIGNAR_LIBRO_PARALELO L3 M1
        1: REACH-GOAL



ext3_problem_4.pddl

step    0: ANYADIR_LIBRO_PREDECESOR_A_LEER L7 L1
        1: ANYADIR_LIBRO_PREDECESOR_A_LEER L1 L2
        2: ASIGNAR_LIBRO_PARALELO L7 M1
        3: ASIGNAR_LIBRO_PREDECESOR L1 M11
        4: ASIGNAR_LIBRO_PREDECESOR L2 M12
        5: ASIGNAR_LIBRO_PARALELO L3 M1
        6: ASIGNAR_LIBRO_PREDECESOR L6 M11
        7: REACH-GOAL



ext3_problem_9.pddl

step    0: ANYADIR_LIBRO_PREDECESOR_A_LEER L1 L2
        1: ANYADIR_LIBRO_PREDECESOR_A_LEER L4 L7
        2: ASIGNAR_LIBRO_PARALELO L1 M1
        3: ASIGNAR_LIBRO_PARALELO L2 M2
        4: ASIGNAR_LIBRO_PARALELO L3 M3
        5: ASIGNAR_LIBRO_PARALELO L4 M3
        6: ASIGNAR_LIBRO_PARALELO L5 M4
        7: ASIGNAR_LIBRO_PREDECESOR L7 M12
        8: REACH-GOAL