(define (problem test) (:domain ext1_planner)
   (:objects L0 L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 - libro
             M1 M2 M3 M4 M5 M6 M7 M8 M9 M10 M11 M12 - mes)
	(:init
		(predecesor L2 L8)
		(predecesor L6 L2)
		(predecesor L6 L8)

		(leer L3)
		(leer L4)
		(leer L8)
		(leer L9)
		(leer L10)

		(leido L1)
		(leido L5)

		(= (ultimo_mes L0) 0)
		(= (ultimo_mes L1) 0)
		(= (ultimo_mes L2) 0)
		(= (ultimo_mes L3) 0)
		(= (ultimo_mes L4) 0)
		(= (ultimo_mes L5) 0)
		(= (ultimo_mes L6) 0)
		(= (ultimo_mes L7) 0)
		(= (ultimo_mes L8) 0)
		(= (ultimo_mes L9) 0)
		(= (ultimo_mes L10) 0)
		(= (ultimo_mes L11) 0)

		(= (numero_mes M1) 1)
		(= (numero_mes M2) 2)
		(= (numero_mes M3) 3)
		(= (numero_mes M4) 4)
		(= (numero_mes M5) 5)
		(= (numero_mes M6) 6)
		(= (numero_mes M7) 7)
		(= (numero_mes M8) 8)
		(= (numero_mes M9) 9)
		(= (numero_mes M10) 10)
		(= (numero_mes M11) 11)
		(= (numero_mes M12) 12)

	)
		(:goal (and
			(forall (?x - libro)
				(or
					(not (leer ?x))
					(asignado ?x)
					(leido ?x)
				)
			)
		)
	)
)